yeoman = require 'yeoman-generator'
chalk  = require 'chalk'
path   = require 'path'

class ProductionGenerator extends yeoman.Base
  writing: =>
    @log "#{chalk.bold.red 'JUST KIDDING! This isn\'t implemented yet.'}"
    throw new Error 'not implemented.'
module.exports = ProductionGenerator
# ---
# generated by js2coffee 2.2.0
